import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonButton,
  IonButtons,
  IonCardTitle,
  IonSearchbar,
  IonContent,
  IonHeader,
  IonTitle,
  IonAvatar,
  IonThumbnail,
  IonTabs,
  IonTabBar,
  IonTabButton,
  IonIcon,
  IonLabel,
  IonItem,
  IonList,
  IonPopover,
  IonToolbar,
  IonInput,
  IonText,
  IonBackButton,
  IonCol,
  IonRow,
  IonBadge,
  IonGrid,
  IonFooter,
  IonSegment, 
  IonSegmentButton,
  IonImg,
  IonSelect, 
  IonSelectOption,
  IonDatetime, 
  IonDatetimeButton,
  IonModal,
  IonTextarea,
  IonMenu,
  IonMenuButton,
  IonCardSubtitle,
  IonApp, IonSplitPane, IonListHeader, IonNote, IonMenuToggle, IonRouterOutlet, IonRouterLink
} from '@ionic/angular/standalone';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    IonContent, IonHeader, IonTitle, CommonModule, FormsModule,
    IonContent,
    IonHeader,
    IonTitle,
    IonToolbar,
    CommonModule,
    FormsModule,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardTitle,
    IonSearchbar,
    IonAvatar,
    IonThumbnail,
    IonTabs,
    IonTabBar,
    IonTabButton,
    IonIcon,
    IonLabel,
    IonItem,
    IonList,
    IonPopover,
    IonInput,
    ReactiveFormsModule,
    IonText,
    IonBackButton,
    IonCol,
    IonRow,
    IonBadge,
    IonGrid,
    IonFooter,
    IonSegment, 
    IonSegmentButton,
    IonImg,
    IonSelect, 
    IonSelectOption,
    IonDatetime, 
    IonDatetimeButton,
    IonModal,
    IonTextarea,
    IonMenu,
    IonButton,
    IonButtons,
    IonMenuButton,
    IonCardSubtitle,
    IonApp, IonSplitPane, IonListHeader, IonNote, IonMenuToggle, IonRouterOutlet, IonRouterLink
  ],
  exports:[IonContent, IonHeader, IonTitle, CommonModule, FormsModule,
    IonContent,
    IonHeader,
    IonTitle,
    IonToolbar,
    CommonModule,
    FormsModule,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardTitle,
    IonSearchbar,
    IonButton,
    IonButtons,
    IonAvatar,
    IonThumbnail,
    IonTabs,
    IonTabBar,
    IonTabButton,
    IonIcon,
    IonLabel,
    IonItem,
    IonList,
    IonPopover,
    IonInput,
    ReactiveFormsModule,
    IonText ,
    IonBackButton,
    IonCol,
    IonRow,
    IonBadge,
    IonGrid,
    IonFooter,
    IonSegment, 
    IonSegmentButton,
    IonImg,
    IonSelect, 
    IonSelectOption,
    IonDatetime, 
    IonDatetimeButton,
    IonModal,
    IonTextarea,
    IonMenu,
    IonMenuButton,
    IonCardSubtitle,
    IonApp, IonSplitPane, IonListHeader, IonNote, IonMenuToggle, IonRouterOutlet, IonRouterLink
  ]
})
export class SharedModule { }
